export { default as Home } from "./Homepage/Home";
export { default as Carts } from "./CartPage/Carts";
export { default as Checkout } from "./Checkout/Checkout";
export { default as Category } from "./Category/Category";
export { default as Details } from "./Product Details/Details";
export { default as OrederPage } from "./OrderPage/OrderPage";
export { default as SearchPage } from "./SearchPage/SearchPage";
export { default as UserDetails } from "./UserDetails/UserDetails";
export { default as Login } from "./Login/Login";
export { default as Signup } from "./Signup/Signup";
